### ISSUE TITLE
Wrong Answer

### ISSUE THREAD

**Issue by akarshgangwar28** [kshitijkat/Wipro-FutureSkills-Preliminary-Programing-Test#1]
The output generated by your code  doesn't  seems right . As it checks only Ist character and last charcter of String but,  question is    show first and last "vowel" in the String,no  matter it present at last or second last.

Example: Input: [Akarsuh, iqqo]
              output:   iqqo    {According to your code} 

.but answer will be : Akarsuhiqqo

**Comment by kshitijkat** [comment]
Thanks for clarification i will update it
